### PR TITLE
Nh/sycamore integration

### PR DESCRIPTION
**Pull request by Noah-Houghton**
Integrates the sycamore function (PR here https://github.com/onnela-lab/forest/pull/119) into Beiwe forest tasks and tableau api endpoint. The function as implemented in forest does have a slightly different API than the extant functions; this implementation assumes that the PR will be merged as is. Alternatively, we could request changes on forest (specifically the naming of kwargs in the sycamore function).

### CODE REVIEW

**Comment by biblicabeebli** [comment]
@Noah-Houghton I'll be the one reviewing this.

several things:
- shift those local imports to the top of the files.
- your IDE / habit-that-I-totally-get is causing whitespace changes in `forest_constants.py`, I'm not seeing it elsewhere though. Please retain (or add if it is missing) whitespace on indentation for this project.
- update the `requirements_data_processing.txt` Forest commit target to one that contains sycamore (or a version number, but I don't think we are there yet).  Note that when there is a git commit target change you may need to pip uninstall Forest and then reinstall it.  (I don't know whence this bug comes, I just know I have to do it on the data processing servers.)
- please rebase this branch off `staged-updates`, not main.
- please squash down (and keep squashed down) your migrations, and since there is custom backfill code rename it to something other than auto_xxx_yyy.  Do not create merge migrations on this project, instead rebuild and rename your custom migration if/when other migrations show up on `staged-updates`.
- Due to some (intentional) automation in the testing suite additions to the daily summaries database table may break tests. The fix should be easy, adding a default value based on field type in `tests/helpers.py`, but let me know if it is not.  The tableau api is aiming for 100% code coverage as it is a critical pathway.

(And finally.... not that this is relevant at all in your code... don't add any usage of the django rest framework to the codebase.)

**Comment by biblicabeebli** [comment]
@clementzach what's a good commit target for testing sycamore code? (branch works too, but branches can be removed so can't be permanent.)

**Comment by Noah-Houghton** [comment]
Hi Eli, good to hear from you again!

>     * shift those local imports to the top of the files.
The local imports are to avoid circular imports. If they were at the top of the file, the program would not run. Does Beiwe have an existing code paradigm to handle cases like this other than local imports? The other option would be to move the `params_dict` out of the model and into a separate file where it could safely import the necessary helper functions.

>     * please squash down (and keep squashed down) your migrations, and since there is custom backfill code rename it to something other than auto_xxx_yyy.  Do not create merge migrations on this project, instead rebuild and rename your custom migration if/when other migrations show up on `staged-updates`.

I can move the modification of the `sycamore_json_string` field to remove null=True into the first migration if you like, but otherwise not sure what you mean by this. My preference is usually to leave migrations alone unless I absolutely have to modify them, but no worries -- I'll go ahead and do that, let me know if you meant something else.

**Comment by biblicabeebli** [comment]
I'll take a look at the imports issue. I thought I handled that, maybe I got interrupted in separating the database declaration from the task runtime.  Or maybe it's something else entirely.

**Comment by biblicabeebli** [comment]
https://github.com/onnela-lab/beiwe-backend/pull/288

imports: Ah, I misidentified the file those imports were in.

The `libs.s3` local import is the exception to the, it is just a really clunky function that always requires a database call. It is not the pattern to follow.

High level, the paradigm is that database declaration files _just can't_ import generic functionality because they are necessarily imported by anything that uses them, including so as to provide typing information. The database declarations are for the purpose of defining database schema, validation, and other database functionality, not generic code.

Please simplify the new filepath getter functions to _only_ provide the correct filepath and shift any additional functionality into the task runner code.

And... add typing information to function calls where possible.

I'll clean up the database queries later, the objects should mostly be available as related fields instead of direct queries.  Let's get the working code out the door first, then I'll clean it up as I debug it on our staging server.

(I know I haven't addressed everything, I'll be back.)

**Comment by biblicabeebli** [comment]
I just rebased on top of the timezone and other general forest cleanup work I got out earlier this week.  That `tz-fixes` branch is going on staging right meow.

It's been at least a week since I looked at this, I may need to pick it or parts of it up soon to get something testable on staging.  It's a longstanding feature that needs to get off the roadmap and into reality.

Part of the "plan" has been to substantially change the task dispatch page, to instead make it multiple pages, one-page-per-forest-task.  This is desirable from a maintenance endpoint and means less frontend work.  Dispatching tasks does not currently have tests due to:
- The current complexity is high.
- A major, half-built feature was missing from the delivered code about a year ago: configurable, savable, portable parameter sets for forest task parameters.  I don't believe the existing parameter saving is workable or extendable, and have not thought through a redesign yet. (I particularly dislike the existing use of a database object that is defined in a migration.)  There also isn't a web interface for editing them or validating them. There is runtime type validation in Forest so we need _something_.
- Lack of familiarity on my part. I did not write this code, so I couldn't just throw down some basic tests back in October like I did with some of the other seemingly complex ones.
- This is the code that uses the django rest framework, which I have banned from this codebase. (This decision is final.) It needs to be changed to use django forms, or just rewritten entirely.  (If we take the least abstract approach of a database model per forest tree we can use modelforms, so maybe that's the best plan.)

**Comment by biblicabeebli** [comment]
more rebasing...

**Comment by biblicabeebli** [comment]
I've done a bunch of cleanup work towards getting the forest parameters remotely viable, other cleanup.  No sycamore functionality yet, but the work to literally run it is technically present, I think.

**Comment by biblicabeebli** [comment]
This branch now works for basic task dispatch, it is deployed to staging, no work other than database cleanup for storing forest task parameters, and it is not enabled.

**Comment by clementzach** [comment]
@biblicabeebli What would be the difficulty in setting up an updated commit hash for running forest on the server? 

Over the weekend I wrote some code to do submission metrics for audio surveys as well as for text surveys. I think that this would probably be useful for future researchers because I think that an audio survey is included in the term "survey". But, if it would take you more than like 30 minutes to include the updated code in the server integration, we could probably just wait until later to include these. 

@hydawo tagging you in case you have any thoughts.

**Comment by biblicabeebli** [comment]
If you mean a web-side selection to pick the commit - lots and lots of work.

If you mean "Eli change it to this commit please" - couple minutes.

If there is consensus of a correct and stable _branch_ to point at - that can be accomplished.

**Comment by biblicabeebli** [comment]
I think I might be misunderstanding you?

**Comment by biblicabeebli** [comment]
any updated commit should include this commit:
https://github.com/onnela-lab/forest/commit/c4e2661e3bc6204488c4cbaa1e1d71162c91a31e
due to this bug: https://github.com/onnela-lab/forest/issues/129

**Comment by clementzach** [comment]
Awesome, I'll get the code I'm working on reviewed and send you an updated commit hash.

**Comment by clementzach** [comment]
@biblicabeebli anything after [this hash](https://github.com/onnela-lab/forest/commit/9f98035cab3d113d4afee0df21e80029ed8c6842) should be fine as far as the Tableau summaries go

**Comment by biblicabeebli** [comment]
@clementzach this is quite old and merged in already

**Pull request merged**
