### PR TITLE
adds csrf protection to all POST requests

### PR DESCRIPTION
**Pull request by Caleb-Dixon**

### CODE REVIEW

**Comment by biblicabeebli** [comment]
Need to add csrf exempt to all endpoints hit by the apps.
Should be everything in api/mobile_api, and also pages/mobile_pages (not actually sure it needs), and api/push_notification

We then need to test on an app that we haven't broken anything.  That's registration, studies, push notifications

**Comment by alvinsiu** [comment]
Not sure why this was closed

**Comment by biblicabeebli** [comment]
this is ancient, we will do csrf after django port using the django csrf library (and automated testing.)

**Comment by zagorsky** [comment]
@alvinsiu I agree with you: this is an important best-practices security update, and we have no timeline for porting the frontend to Django.  But I can't reopen the PR because `development` got deleted, and I can't rebase/cherry-pick this onto `main` without spending a chunk of time resolving merge conflicts.  I just don't have time to address this right now.

**Comment by biblicabeebli** [comment]
This was me, I'll deal with getting github to behave.  I've re-pushed the commit and the branch (I have an up-to-date pull from just before removing the branch) but it looks like that's not enough for github to allow us to reopen. can't address that until after I post this.

Sorry to cause a fuss, I thought this PR was old and forgotten and I honestly didn't expect anybody to care.

What I meant-but-was-utter-crap-at-stating in my post is that I am working on the django port, and that adding CSRF protection site-wide will be a feature I incorporate into that port.  I have a lot of experience with django csrf, and I've done the research on how to make jinja work with the django csrf tag.  In my opinion

I started the django port the weekend before last week, you can check its progress on branch eli/django.  It is just-barely functional right now for some admin pges, but even getting to the point of staging-ready is weeks-out.  **But** it is started!

I will deal with any emergent complexities of new code pushed to master, I'm keeping my branch rebased on top of it.

**Pull request closed without merging**
