### PR TITLE
Enable encryption of data at rest

### PR DESCRIPTION
**Pull request by erinn**
Given the data you folks consume, and given that encryption of data in AWS creates basically zero overhead: 'You can expect the same IOPS performance on encrypted volumes as on unencrypted volumes, with a minimal effect on latency. ' (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html) I can't see any reason why encryption would not be enabled.

Sorry about the spacing changes, atom editor just does that by default, I can change that around if it is a big deal. The important line is 225.

### CODE REVIEW

**Comment by biblicabeebli** [comment]
This seems like a no-brainer good thing thing to do, and based on my own experience with RDS encryption since developing this code it _should_ be painless. I definitely want to merge this in if that holds true

I do have a concern which is that I thought/ I think RDS requires adding integration with AWS KMS (key management service), for which there is currently no code, and if we need to develop that we will probably also need to update the aws permissions. (maybe)

Additionally, since this is a change to a core component we need to test a full cluster deployment....

I'm on my commute right now, will try and check in in this again soon, just a busy week for me.  Any research you can do on addressing my comments above would be appreciated!

(And thank you for contributing!)

**Comment by erinn** [comment]
Yeah I believe you are correct. I was under the assumption that it was a bit easier than that, AWS would use the login credentials or some such as the key, but KMS is in fact required (as far as I can tell). It doesn't look like much of a KMS setup is required, but it would require additional calls to create.

**Comment by erinn** [comment]
I'll be working on coding this up fully and I'll update the PR accordingly.

**Comment by erinn** [comment]
I can now confirm, with pretty high confidence, that no setup is required for KMS in AWS to use encryption. By setting the booleans to true to enable encryption, AWS will by default generate the CMK required. So with the above commits, RDS is encrypted at rest and two of the three EBS volumes, for the manager and the worker are encrypted by default. This is a large win for little (coding) effort. You can test yourself by bringing up a cluster in a different region as KMS is region specific. 

I'll continue to work on getting the initial elasticbeanstalk instance's EBS volume encrypted. 

Further steps on my check list for this PR are to encrypt the S3 bucket.

In other PRs I will be working to encrypt communications between the app and RDS, as well as communications from the ELB to the web server.

-Erinn

**Comment by biblicabeebli** [comment]
Awesome, and thanks for the research.

Code looks fine, and there's no elegant way to represent those annoying, nested, boto3 parameter data structures so don't worry about that.

(oooo, ApplyServerSideEncryptionByDefault, sounds perfect. I've not seen it before, do you know when that was introduced?)

Have you tested this with a deployment that has then had a device register and upload data, and then tried to view the data either is a shell session or as downloaded data?  I recall some minimal work down these lines that I would have done perhaps a year ago, and I believe libs.s3 in the server code will need a corresponding update, but perhaps it is the case that that is what ApplyServerSideEncryptionByDefault fixes.  If so then there also needs to be some detection for compatibility of existing servers, which probably means updates to the config/__init__.py....


As for merging your work into master (the staging and production branches are irrelevant for cluster management updates, and this is even more constrained) I am concerned about introducing an intermediate stage of development for your larger encryption work.  I want to avoid scenarios that might be incredibly hard on a system administrator to rectify, like a half-encrypted deployment.  Your thoughts and opinions?  Any catastrophic scenarios based on your other ongoing work you can conceive of?

**Comment by erinn** [comment]
Not sure when that API call was introduced. 

There is also a new option, I'm referring to as the 'nuclear option': https://aws.amazon.com/blogs/aws/new-opt-in-to-default-encryption-for-new-ebs-volumes/ it is probably a good idea for projects like this. I'm currently struggling with how to get the elasticbeanstalk instances to encrypt EBS by default, the above fixes that, but it feels a bit sledgehammery to me, and requires everything in the region to use encryption, which is probably a great idea, but could lead to havoc if you have a lot of other things deployed in the region and for some reason they have to have unencrypted storage (though I struggle to imagine why that would be the case).

All encryption of data at rest should be basically transparent to the application. I imagine AWS has this implemented in hardware accelerators which is why they can guarantee no performance hit for encryption. Anyway, long story short, I don't believe any client changes will be necessary, it'll just work. That being said testing is always a good thing. We currently only have a test setup with your original code that a researcher is working on, so I can't speak to it operationally yet. After I sew up the last of the encryption at rest work I'll probably tear down the existing cluster and rebuild with this in place, it'll be a good test bed. If you have time though, I'd sure appreciate another set of eyes on it, as I just started looking into this thing a week ago.

As for merging, I believe each of these steps is better than the last but there is nothing wrong with remaining on the last step. 'You have encrypted data at rest?' Great! That's one step better than nothing. However, I'll be developing all of this in the next week or so, as three separate PRs and I'll merge them all together in my master, so if you want to hold off and merge them all at once I reckon that'll work too. The PRs should not be dependent on each other, it is simply a logical break down of work so it doesn't come in as one huge lump.

Unless someone tries to deploy this on top of an existing cluster, I don't see any disaster lurking here. Even trying to deploy on top of an existing will probably fail out before anything bad can happen.

**Comment by erinn** [comment]
It very much looks like encryption of the elastic beanstalk instance's root volume isn't (easily) possible. There are two ways to make it work, use an encrypted AMI, which creates a huge amount of overhead and probably isn't feasible for most users of this project, or use the aforementioned:  https://aws.amazon.com/blogs/aws/new-opt-in-to-default-encryption-for-new-ebs-volumes/ which interestingly works, implying that it should be possible to do via an API, but I sure can't figure out how to do it at this point.

I wouldn't be comfortable forcing an entire regions EBS stores to be encrypted, even though it is in general a good idea. So perhaps a note can be added to the deploy guide showing how to access the feature and that it is probably a good idea to enable?

In this last commit I've enabled encryption of the s3 bucket used by EB, it isn't perfect as EB creates the bucket, puts a couple of things in it that are not encrypted then the policy is activated to force encryption at rest. As well, you may want to take a look as to whether you want the log message I placed in there, I don't want to cloud up the end of your run. 

This probably completes my work on encrypting data at rest. I'll be moving on with two more PRs one for app -> RDS encryption the other for ELB -> app. 

This isn't fully tested yet, so not ready to merge at the moment. If you have time, please test. Data at rest  encryption in AWS is fairly transparent, so I doubt there will be issues, but once I am done with all three PRs I'll merge them into my master do a fully deploy and examine the results carefully.

**Comment by erinn** [comment]
I have now tested this and it is working for me. I would prefer if someone else tried it out as well.

**Comment by biblicabeebli** [comment]
Hi!
Sorry about being slow on responding.
I agree with your assessment.
I would like to merge this.  It really only applies to the deploy operation, but I will want to test on a staging server running an instance that is not encrypted to see if any new and exciting issues crop up.

**Comment by biblicabeebli** [comment]
This has been merged into the python 3 upgrades branch, testing will occur along with deployment debugging for python 3.

**Pull request merged**
