### PR TITLE
Implement CSRF protection

### PR DESCRIPTION
**Pull request by Caleb-Dixon**
adds cross site request forgery protection to all forms in the application

### CODE REVIEW

**Comment by alvinsiu** [comment]
We're also going to need to add csrf exempt decorators on endpoints that don't need this

**Comment by biblicabeebli** [comment]
Need this branch rebased on development, which now includes all content from the Veracode security audit.

The other branch from Caleb for XSS attacks was **_very_** unhappy about merging and I eventually had to rework that code manually.

FYI the Veracode work is stalled due to process, there will inevitably be more work from that.

**Comment by alvinsiu** [comment]
@Caleb-Dixon Non-urgently, when you get the chance, could you rebase this as pre Eli's request? Thanks!

**Comment by Caleb-Dixon** [comment]
Will do. I misunderstood the previous email and did not realize that it was
a request for me to do that. I should have time to do that later today.

**Pull request closed without merging**
