### PR TITLE
Fix copy study relative schedules

### PR DESCRIPTION
**Pull request by biblicabeebli**
This is the branch and changes I put together to fix the bug where relative surveys result in a pointer to a survey in the wrong study on scheduled events and their archives.

Could you comment on whether we should put together a migration to attempt to fix existing scheduled events that have crossed pointers?  I don't think we have push notifications functional enough external to our production servers to justify the time and effort commitment.

### CODE REVIEW

**Comment by biblicabeebli** [comment]
@zagorsky I'm pretty sure this code is good, I tried to be thorough and careful, I think this should get pushed to master asap, ideally along with #234

**Review by zagorsky — CHANGES_REQUESTED** [review]
@biblicabeebli the code looks good, and I've tested three scenarios: copying from old-format JSON, copying from new-format JSON, and copying directly (when creating the new study, checking the checkbox that says "copy ... from an existing study").  The JSON copy functionality works fine (except for one bug I fixed in 6ca5ed8), but there are two problems with the direct copy functionality:

- [ ] It copies all surveys, including the deleted ones.  It should ignore the deleted ones.
- [ ] It copies the intervention dates, but doesn't link the survey schedules to them.  I copied a relative schedule survey and it said "1 day after undefined".

Could you please fix those two, then ask me to test again?  I think then this PR will be ready to merge.

**Comment by biblicabeebli** [comment]
First one should be done, just adding a filter over in the URL endpoint, commit bf66edc77ab4a525582b0007e815d86d69d5727f

**Comment by biblicabeebli** [comment]
- It copies the intervention dates, but doesn't link the survey schedules to them. I copied a relative schedule survey and it said "1 day after undefined".

(I think you meant just interventions)

I ended up doing a refactor because I just couldn't follow the code, and there were separate code-paths for local copying and json copying.  Result of the refactor is that we now have 1 place where we serialize, 1 place where we deserialize, and both local and json use exactly the same code because local exports and then imports.

Comment: I considered rewriting this using the rest framework serializer, but determined that maintaining a custom serializer for these database objects would actually be a higher maintenance burden than just converting to a unified code path.

I think its 100% correct now.  I was able to replicate a bug similar-but-not-identical to the one you described beforehand, and now it seems to be working fine with the relative schedules.

The diff..... could be worse...

Need to test cloning off of an old-style json blob, I'm on a different computer than before and don't have the old one.  Could you please test that?  I'm so sick of this particular part of the code.

**Comment by zagorsky** [comment]
>> It copies the intervention dates, but doesn't link the survey schedules to them...

> (I think you meant just interventions)

Yep, you're correct- my mistake!

**Review by zagorsky — APPROVED** [review]
Looks good to me!  I tested all three scenarios: copy study directly, copy study from old-format JSON, copy study from new-format JSON, and all worked correctly for me.  Thanks for your work on this!  Also, I think the new way you did it is a little cleaner.

**Pull request merged**
